# Generated by Django 5.2.7 on 2025-10-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_expense_currency_alter_income_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro (€)'), ('UAH', 'Ukrainian Hryvnia (₴)'), ('USD', 'US Dollar ($)'), ('GBP', 'British Pound (£)'), ('JPY', 'Japanese Yen (¥)'), ('CAD', 'Canadian Dollar (C$)'), ('AUD', 'Australian Dollar (A$)')], default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='income',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro (€)'), ('UAH', 'Ukrainian Hryvnia (₴)'), ('USD', 'US Dollar ($)'), ('GBP', 'British Pound (£)'), ('JPY', 'Japanese Yen (¥)'), ('CAD', 'Canadian Dollar (C$)'), ('AUD', 'Australian Dollar (A$)')], default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro (€)'), ('UAH', 'Ukrainian Hryvnia (₴)'), ('USD', 'US Dollar ($)'), ('GBP', 'British Pound (£)'), ('JPY', 'Japanese Yen (¥)'), ('CAD', 'Canadian Dollar (C$)'), ('AUD', 'Australian Dollar (A$)')], default='EUR', max_length=3),
        ),
    ]
