"""
Django settings for homeaccountant project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR is the root directory of the Django project.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# A secret key for cryptographic signing. Keep this confidential in production.
SECRET_KEY = 'django-insecure-1-eioy6%_77&4&w-)j%tr_137-15&z!qp)b*-kgjnhp3n5n#bc'

# SECURITY WARNING: don't run with debug turned on in production!
# Enables/disables debug mode. Set to False in production for security and performance.
DEBUG = True

# A list of strings representing the host/domain names that this Django site can serve.
ALLOWED_HOSTS = []


# Application definition

# List of Django applications enabled in this project.
INSTALLED_APPS = [
    'django.contrib.admin',  # The admin site.
    'django.contrib.auth',  # Authentication system.
    'django.contrib.contenttypes',  # Content type system.
    'django.contrib.sessions',  # Session management.
    'django.contrib.messages',  # Messaging framework.
    'django.contrib.staticfiles',  # Static files management.
    'expenses',  # Our custom expenses application.
]

# Middleware classes that process requests and responses.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# The full Python path to the root URLconf.
ROOT_URLCONF = 'homeaccountant.urls'

# Configuration for Django's template engine.
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # Directories where Django will look for templates.
        'APP_DIRS': True,  # Allows Django to look for templates inside app directories.
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# The full Python path of the WSGI application object.
WSGI_APPLICATION = 'homeaccountant.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database configuration. Using SQLite for simplicity.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',  # Path to the SQLite database file.
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# List of validators used to check the strength of user passwords.
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# Language code for this installation.
LANGUAGE_CODE = 'en-us'

# Time zone for this installation.
TIME_ZONE = 'UTC'

# Enable Django's translation system.
USE_I18N = True

# Enable timezone support.
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# URL to use when referring to static files (e.g., /static/css/base.css).
STATIC_URL = 'static/'
# List of locations where the staticfiles app will look for additional static files.
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
# The absolute path to the directory where collectstatic will gather all static files for deployment.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# Type of auto-created primary keys.
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Specifies our custom User model as the authentication model.
AUTH_USER_MODEL = 'expenses.User'

# URL to redirect to after a user logs in.
LOGIN_REDIRECT_URL = '/'
# URL to redirect to after a user logs out.
LOGOUT_REDIRECT_URL = '/'
